-- Info 配置信息表
CREATE TABLE IF NOT EXISTS info (
    `key` VARCHAR(255) PRIMARY KEY COMMENT '配置键',
    `value` JSON COMMENT '配置值',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配置信息表';